name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - id: 'install'
        name: install
        run: yarn
      - id: 'build'
        name: build
        run: yarn build
        if: ${{ steps.install.outcome == 'success' }}
      - id: 'publish'
        run: yarn publish
        if: ${{ steps.build.outcome == 'success' }}
